Controllers/SinhVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DiemCong_NguyenVietHoang.Models;

namespace DiemCong_NguyenVietHoang.Controllers
{
    public class SinhVienController : Controller
    {
        // GET: SinhVien
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult Index()
        {
            var all_sinhvien = from tt in data.SinhViens select tt;
            return View(all_sinhvien);
        }

        // Detail
        public ActionResult Detail(int id)
        {
            var D_Sinhvien = data.SinhViens.Where(m => m.MaSV == id).First();
            return View(D_Sinhvien);
        }
        
        //Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, SinhVien sv)
        {
            var ten = collection["HoTen"];
            if (string.IsNullOrEmpty(ten))
            {
                ViewData["Error"] = "Dont empty!";
            }
            else
            {
                sv.HoTen = ten;
                data.SinhViens.InsertOnSubmit(sv);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }
    }
}

Views/SinhVien/Create.cshtml
@model DiemCong_NguyenVietHoang.Models.SinhVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SinhVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNganh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNganh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNganh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/SinhVien/Index.cshtml
@model IEnumerable<DiemCong_NguyenVietHoang.Models.SinhVien>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sinh viên</h2>
@Html.ActionLink("Create New", "Create", "SinhVien")
<table border="1">
    <tr>
        <th>Ma sinh vien</th>
        <th>Ho ten</th>
        <th>Gioi tinh</th>
        <th>Ngay sinh</th>
        <th>Hinh</th>
        <th>MaNganh</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    { 
        <tr>
            <td>@item.MaSV</td>
            <td>@item.HoTen</td>
            <td>@item.GioiTinh</td>
            <td>@item.NgaySinh</td>
            <td><img src="@item.Hinh" width="150px" /></td>
            <td>@item.MaNganh</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaSV }) |
                @Html.ActionLink("Detail", "Detail", new { id = item.MaSV }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaSV }) 
            </td>
        </tr>
    }
</table>